export const config = {
  name: 'WINMAX', company: 'WINMAX INOVASI', legalName: 'PT WINMAX INOVASI INDONESIA',
  origin: 'https://winmax.jason00180018.chatgpt.site',
  workbench: 'https://carefor-operations.jason00180018.chatgpt.site',
  chinaEmail: '13302552538@163.com', indonesiaEmail: 'jason00180018@gmail.com',
  instagram: 'https://www.instagram.com/bbso.id/', tiktok: 'https://www.tiktok.com/@bbso.babyshop'
};
export const languages = {
 zh: {
  htmlLang:'zh-CN', other:'id', label:'中文', otherLabel:'Bahasa Indonesia',
  meta:'WINMAX INOVASI：面向印尼市场的进口贸易、品牌分销、自有品牌与零售业务。了解 BB-SO、99K、Carefor、宝体安与 Mimimilo。',
  nav:[['','首页'],['about','集团介绍'],['bbso','BB-SO 母婴零售'],['99k','99K 时尚零售'],['trade','进口贸易'],['brands','品牌中心'],['careers','招聘'],['contact','联系我们']],
  menu:'打开导航', closeMenu:'关闭导航', skip:'跳转到正文', home:'首页', workbench:'工作台入口', more:'了解更多', allBrands:'查看品牌中心',
  hero:{eyebrow:'WINMAX INOVASI · INDONESIA',title:['优质产品','美好生活'],subtitle:'Better Products. Better Life.',text:'连接品牌、贸易与零售，为印尼家庭带来更多生活选择。',action:'认识 WINMAX',caption:'BB-SO · 门店实景'},
  businessEyebrow:'OUR BUSINESS',businessTitle:'从品牌，走进日常生活。',businessText:'以进口贸易连接产品，以零售连接消费者，让品牌在印尼市场生长。',
  businesses:[
   {name:'BB-SO',tag:'自有品牌 · 母婴零售',title:'陪伴家庭的每一步成长',body:'由 PT Bunda Little Blessing 运营的自有母婴零售品牌，围绕宝宝与家庭的日常所需，连接实体门店与线上购物。',path:'bbso',image:'bbso-store.jpg',alt:'BB-SO Baby Shop 门店外观',color:'orange'},
   {name:'99K',tag:'加盟业务 · 时尚零售',title:'让日常穿搭多一种选择',body:'通过女装零售加盟业务，参与印尼时尚消费市场。以门店场景呈现服饰与日常穿搭选择。',path:'99k',image:'99k-store.jpg',alt:'99K Premium Collection Store 门店',color:'rust'},
   {name:'WINMAX',tag:'进口贸易 · 品牌分销',title:'全球产品，本地连接',body:'围绕品牌引进、产品供应与渠道合作，连接中国品牌与印尼市场，支持品牌的本地化经营。',path:'trade',color:'blue'}
  ],
  brandsEyebrow:'BRANDS & PARTNERS',brandsTitle:'多元品牌，共同成长。',brandsText:'自有品牌、代理品牌与加盟业务，各有专长，也有共同的生活视角。',
  brands:[
   {slug:'carefor',name:'Carefor',category:'母婴护理',relation:'印尼独家代理',description:'来自中国的母婴护理品牌，围绕宝宝日常清洁与护理，为家庭提供产品选择。',color:'pink'},
   {slug:'nutrition',name:'宝体安',category:'营养产品',relation:'品牌引进规划',description:'围绕益生菌与营养产品开展品牌引进规划，产品信息以正式发布资料为准。',color:'orange'},
   {slug:'mimimilo',name:'Mimimilo',category:'童装 · 童鞋',relation:'自有品牌孵化',description:'以现有线上店铺为起点，规划童装与童鞋品类，逐步发展自有品牌。',color:'teal'}
  ],
  aboutEyebrow:'ABOUT WINMAX',aboutTitle:'扎根印尼，连接更多可能。',aboutLead:'WINMAX INOVASI 以进口贸易、自有品牌与零售业务为发展方向，将产品供应、品牌经营和消费场景相连接。',
  values:[['关注家庭','围绕家庭的日常所需，理解不同成长阶段的生活选择。'],['认真经营','从产品信息到门店服务，重视每一个具体环节。'],['携手成长','与品牌方、供应商及渠道伙伴建立持续的合作关系。']],
  aboutPage:{title:'认识 WINMAX INOVASI',intro:'在印尼，连接品牌与生活。',body:'PT WINMAX INOVASI INDONESIA 是 WINMAX 的总部公司。我们的业务涵盖进口贸易、品牌分销、自有品牌发展及零售参与，通过不同业务板块服务印尼市场。',structureTitle:'集团与业务关系',structureLead:'各业务板块的品牌属性与经营角色清晰区分。',rows:[['WINMAX INOVASI','总部 · PT WINMAX INOVASI INDONESIA'],['BB-SO','自有母婴零售品牌 · PT Bunda Little Blessing'],['99K','女装时尚零售 · 加盟投资业务'],['WINMAX Import & Distribution','进口贸易、品牌代理与渠道合作'],['Mimimilo','自有品牌孵化 · 童装与童鞋规划']],vision:'愿景',visionText:'让值得信赖的产品与品牌，走进更多印尼家庭的日常生活。',mission:'使命',missionText:'连接产品与市场，将品牌经营、供应链协作与零售服务落实到日常工作。'},
  bbso:{title:'BB-SO 母婴零售',intro:'陪伴宝宝成长，也关心每一个家庭。',body:'BB-SO 是 PT Bunda Little Blessing 的自有母婴零售品牌。我们通过实体门店与线上渠道，提供母婴家庭日常所需的产品选择。',section:'围绕日常所需',categories:[['喂养与营养','奶粉、喂养用品及相关家庭需求。'],['清洁与护理','纸尿裤、洗护用品与宝宝日常护理。'],['穿着与生活','宝宝服饰、生活用品与成长阶段的日常选择。']],network:'线下与线上，一起服务家庭',stores:[['Kalibata Mall','BB-SO 母婴零售门店'],['Cengkareng','BB-SO 母婴零售门店']],online:'关注 BB-SO',onlineText:'通过 BB-SO 的品牌社交账号了解产品与门店动态。',photoCaption:'BB-SO 门店实景；照片中的活动信息仅为拍摄当时展示。'},
  fashion:{title:'99K 时尚零售',intro:'日常穿搭，也可以有新的灵感。',body:'99K 是我们的女装时尚零售加盟投资业务。通过加盟零售场景参与印尼市场，连接服饰选择与日常生活。',section:'时尚零售加盟业务',items:[['品牌关系','99K 以加盟形式参与集团零售业务。'],['零售场景','围绕女装陈列、日常穿搭与到店购物体验展开。'],['业务联系','有关集团的零售合作，可通过总部公布的邮箱联系。']],caption:'99K 门店实景；照片中的促销与价格不代表当前活动。'},
  trade:{title:'进口贸易与品牌分销',intro:'连接全球产品，服务印尼市场。',body:'WINMAX 围绕进口贸易、品牌代理与产品供应开展业务，通过品牌引进、渠道合作与线上线下零售，建立产品与本地市场的联系。',section:'从品牌引进到本地经营',steps:[['品牌合作','了解产品定位、品牌规划与印尼市场需求。'],['供应链协作','围绕选品、供应与贸易环节开展合作。'],['渠道连接','结合品牌特性，衔接分销、线上及线下零售场景。']],careforTitle:'Carefor · 母婴护理',careforBody:'作为 Carefor 在印尼的独家代理，开展品牌与产品的本地市场经营。',network:'渠道合作',networkText:'欢迎品牌方、供应商和零售渠道伙伴，就产品引进、分销及市场合作与 WINMAX 联系。'},
  brandPage:{title:'品牌中心',intro:'面向家庭、时尚与健康的多元选择。',body:'了解 WINMAX 业务中的品牌与合作关系。自有品牌、代理品牌及加盟业务分别以其对应角色开展经营。',retailTitle:'零售品牌与业务',retailText:'BB-SO 是自有母婴零售品牌；99K 为女装零售加盟业务。'},
  brandDetails:{
   carefor:{title:'Carefor 母婴护理',intro:'关注宝宝日常清洁与护理。',body:'Carefor 来自中国。WINMAX 作为其印尼独家代理，负责在本地市场开展品牌与产品经营。',facts:[['合作关系','印尼独家代理'],['品类方向','宝宝清洁与日常护理'],['展示产品','婴儿油、洗发、润肤及沐浴产品']],note:'产品规格、适用范围与使用方法，请以具体产品的正式标签和说明为准。',image:'carefor-products.jpg',alt:'Carefor Baby 婴儿油、洗发、润肤与沐浴产品实拍',rotate:true},
   nutrition:{title:'宝体安 · 营养产品',intro:'关注家庭的营养需求。',body:'宝体安益生菌与营养产品是 WINMAX 的品牌引进规划方向之一。后续产品系列与市场安排，将以正式确认的资料为准。',facts:[['品类方向','益生菌与营养产品'],['当前阶段','品牌引进规划'],['产品信息','正式资料确认后更新']],note:'本页面为业务方向介绍，不构成产品功效或健康建议。'},
   mimimilo:{title:'Mimimilo 自有品牌',intro:'从线上店铺，逐步建立品牌。',body:'Mimimilo 是我们的自有品牌孵化方向。以现有 Mimilo 线上店铺为起点，规划童装、童鞋等品类，逐步形成品牌与产品体系。',facts:[['品牌关系','自有品牌孵化'],['现有基础','Mimilo 线上店铺'],['规划品类','童装与童鞋']],note:'新品牌产品与上线安排，以后续正式发布为准。'}
  },
  careers:{title:'与 WINMAX 一起成长',intro:'在品牌、贸易与零售的日常工作中，发挥你的专长。',body:'我们关注认真做事、愿意学习、理解顾客与团队协作的人。以下为团队工作方向；具体在招岗位、职责及待遇以招聘沟通为准。',areas:[['品牌与业务拓展','品牌沟通、渠道合作与市场执行。'],['电商运营','产品展示、内容运营与线上零售。'],['门店与零售服务','商品陈列、顾客服务与门店日常运营。']],applyTitle:'介绍一下你自己',applyBody:'可将个人简历与意向岗位发送至印尼联系邮箱。请在邮件主题注明姓名和意向岗位。',button:'邮件联系招聘',subject:'WINMAX 求职意向 — 姓名 / 岗位'},
  contact:{title:'联系 WINMAX',intro:'欢迎交流，把下一步合作落到实处。',body:'品牌引进、供应链、零售合作或招聘咨询，请通过以下邮箱与我们联系。',china:'中国联系',indonesia:'印尼联系',email:'写邮件',subject:'WINMAX 合作咨询',company:'总部公司',location:'业务市场',locationValue:'印度尼西亚',topics:[['品牌与供应链','品牌代理、产品供应和进口贸易合作。'],['渠道与零售','分销渠道、门店及零售业务合作。'],['团队与招聘','了解公司及相关岗位工作方向。']],prompt:'邮件中请注明姓名、公司或所在地区，以及希望交流的事项，方便我们了解你的需求。'},
  ctaTitle:'一起探索下一步合作。',ctaBody:'品牌、供应链与零售的连接，从一次交流开始。',ctaButton:'联系我们',
  footerTagline:'Better Products. Better Life.',footerText:'品牌 · 贸易 · 零售',footerNav:'了解 WINMAX',footerContact:'联系邮箱',rights:'保留所有权利。',external:'在新窗口打开',notFound:'没有找到这个页面',notFoundBody:'你可以回到首页，继续了解 WINMAX。'
 },
 id: {
  htmlLang:'id',other:'zh',label:'ID',otherLabel:'中文',
  meta:'WINMAX INOVASI menghubungkan impor, distribusi merek, pengembangan merek sendiri, dan ritel di Indonesia. Kenali BB-SO, 99K, Carefor, 宝体安, dan Mimimilo.',
  nav:[['','Beranda'],['about','Tentang Kami'],['bbso','BB-SO'],['99k','99K'],['trade','Impor & Distribusi'],['brands','Merek'],['careers','Karier'],['contact','Kontak']],
  menu:'Buka navigasi',closeMenu:'Tutup navigasi',skip:'Langsung ke konten',home:'Beranda',workbench:'Portal Tim',more:'Selengkapnya',allBrands:'Kenali merek kami',
  hero:{eyebrow:'WINMAX INOVASI · INDONESIA',title:['Produk bermutu.','Hidup lebih baik.'],subtitle:'Better Products. Better Life.',text:'Menghubungkan merek, perdagangan, dan ritel untuk menghadirkan lebih banyak pilihan bagi keluarga Indonesia.',action:'Kenali WINMAX',caption:'BB-SO · Foto gerai'},
  businessEyebrow:'OUR BUSINESS',businessTitle:'Dari merek, hadir dalam keseharian.',businessText:'Menghubungkan produk melalui perdagangan dan pelanggan melalui ritel, agar merek tumbuh di Indonesia.',
  businesses:[
   {name:'BB-SO',tag:'Merek sendiri · Ritel ibu & bayi',title:'Menemani keluarga bertumbuh',body:'Merek ritel ibu dan bayi milik PT Bunda Little Blessing, melayani kebutuhan sehari-hari melalui gerai dan kanal belanja online.',path:'bbso',image:'bbso-store.jpg',alt:'Tampak depan gerai BB-SO Baby Shop',color:'orange'},
   {name:'99K',tag:'Usaha waralaba · Ritel fesyen',title:'Pilihan untuk gaya sehari-hari',body:'Partisipasi dalam pasar fesyen Indonesia melalui investasi usaha ritel waralaba pakaian wanita.',path:'99k',image:'99k-store.jpg',alt:'Gerai 99K Premium Collection Store',color:'rust'},
   {name:'WINMAX',tag:'Impor · Distribusi merek',title:'Produk global, koneksi lokal',body:'Menghubungkan merek dari Tiongkok dengan pasar Indonesia melalui pengadaan produk, kerja sama kanal, dan pengelolaan merek lokal.',path:'trade',color:'blue'}
  ],
  brandsEyebrow:'BRANDS & PARTNERS',brandsTitle:'Beragam merek, tumbuh bersama.',brandsText:'Merek sendiri, merek yang diwakili, dan usaha waralaba dengan peran yang berbeda dalam kehidupan sehari-hari.',
  brands:[
   {slug:'carefor',name:'Carefor',category:'Perawatan ibu & bayi',relation:'Agen eksklusif Indonesia',description:'Merek perawatan ibu dan bayi dari Tiongkok, dengan pilihan produk untuk kebersihan dan perawatan harian si kecil.',color:'pink'},
   {slug:'nutrition',name:'宝体安',category:'Produk nutrisi',relation:'Rencana pengembangan pasar',description:'Arah pengembangan merek probiotik dan nutrisi. Informasi produk mengikuti materi yang telah dikonfirmasi secara resmi.',color:'orange'},
   {slug:'mimimilo',name:'Mimimilo',category:'Pakaian & sepatu anak',relation:'Pengembangan merek sendiri',description:'Berawal dari toko online yang sudah berjalan, dengan rencana kategori pakaian dan sepatu anak.',color:'teal'}
  ],
  aboutEyebrow:'ABOUT WINMAX',aboutTitle:'Berakar di Indonesia. Terhubung lebih jauh.',aboutLead:'WINMAX INOVASI berfokus pada perdagangan impor, merek sendiri, dan ritel, menghubungkan pasokan produk, pengelolaan merek, dan kebutuhan konsumen.',
  values:[['Peduli keluarga','Memahami kebutuhan sehari-hari di setiap tahap pertumbuhan keluarga.'],['Bekerja dengan sungguh-sungguh','Memperhatikan setiap detail, dari informasi produk hingga layanan gerai.'],['Bertumbuh bersama','Membangun kerja sama yang berkelanjutan dengan merek, pemasok, dan mitra kanal.']],
  aboutPage:{title:'Mengenal WINMAX INOVASI',intro:'Menghubungkan merek dan kehidupan di Indonesia.',body:'PT WINMAX INOVASI INDONESIA merupakan perusahaan induk WINMAX. Bidang usaha kami meliputi perdagangan impor, distribusi merek, pengembangan merek sendiri, dan partisipasi dalam ritel untuk pasar Indonesia.',structureTitle:'Struktur & bidang usaha',structureLead:'Setiap bidang usaha memiliki hubungan merek dan peran operasional yang berbeda.',rows:[['WINMAX INOVASI','Perusahaan induk · PT WINMAX INOVASI INDONESIA'],['BB-SO','Merek ritel ibu & bayi sendiri · PT Bunda Little Blessing'],['99K','Ritel fesyen wanita · Investasi usaha waralaba'],['WINMAX Import & Distribution','Perdagangan impor, keagenan merek, dan kerja sama kanal'],['Mimimilo','Pengembangan merek sendiri · Rencana pakaian & sepatu anak']],vision:'Visi',visionText:'Membawa produk dan merek yang dapat dipercaya ke dalam keseharian lebih banyak keluarga Indonesia.',mission:'Misi',missionText:'Menghubungkan produk dengan pasar melalui pengelolaan merek, kolaborasi rantai pasok, dan layanan ritel sehari-hari.'},
  bbso:{title:'BB-SO, untuk ibu & bayi',intro:'Menemani tumbuh kembang si kecil dan kebutuhan keluarga.',body:'BB-SO adalah merek ritel ibu dan bayi milik PT Bunda Little Blessing. Gerai dan kanal online kami menghadirkan pilihan produk untuk kebutuhan keluarga sehari-hari.',section:'Berfokus pada kebutuhan sehari-hari',categories:[['Makan & nutrisi','Susu, perlengkapan makan, dan kebutuhan keluarga terkait.'],['Kebersihan & perawatan','Popok, produk kebersihan, dan perawatan harian bayi.'],['Pakaian & perlengkapan','Pakaian bayi serta perlengkapan untuk berbagai tahap pertumbuhan.']],network:'Gerai dan kanal online, bersama melayani keluarga',stores:[['Kalibata Mall','Gerai ritel ibu & bayi BB-SO'],['Cengkareng','Gerai ritel ibu & bayi BB-SO']],online:'Ikuti BB-SO',onlineText:'Temukan kabar produk dan gerai melalui akun media sosial BB-SO.',photoCaption:'Foto gerai BB-SO. Informasi acara pada foto berlaku pada waktu pengambilan gambar.'},
  fashion:{title:'99K, ritel fesyen',intro:'Inspirasi baru untuk gaya sehari-hari.',body:'99K adalah investasi usaha ritel waralaba pakaian wanita kami. Melalui gerai waralaba, kami berpartisipasi dalam pasar fesyen Indonesia.',section:'Usaha ritel melalui waralaba',items:[['Hubungan merek','99K menjadi bagian dari kegiatan ritel melalui skema waralaba.'],['Pengalaman ritel','Pilihan pakaian wanita, penataan produk, dan belanja langsung di gerai.'],['Hubungi kami','Untuk kerja sama ritel dengan grup, silakan gunakan email perusahaan yang tercantum.']],caption:'Foto gerai 99K. Promosi dan harga dalam foto tidak mewakili penawaran saat ini.'},
  trade:{title:'Impor & distribusi merek',intro:'Produk global untuk pasar Indonesia.',body:'WINMAX menjalankan kegiatan perdagangan impor, keagenan merek, dan pasokan produk. Pengembangan merek, kerja sama kanal, serta ritel online dan offline menghubungkan produk dengan pasar lokal.',section:'Dari pengembangan merek ke pasar lokal',steps:[['Kerja sama merek','Memahami posisi produk, rencana merek, dan kebutuhan pasar Indonesia.'],['Kolaborasi pasokan','Bekerja sama dalam pemilihan produk, pasokan, dan perdagangan.'],['Koneksi kanal','Menghubungkan karakter merek dengan distribusi, ritel online, dan gerai.']],careforTitle:'Carefor · Perawatan ibu & bayi',careforBody:'Sebagai agen eksklusif Carefor di Indonesia, kami mengembangkan kegiatan merek dan produk di pasar lokal.',network:'Kerja sama kanal',networkText:'Kami terbuka untuk berdiskusi dengan pemilik merek, pemasok, dan mitra ritel mengenai pengembangan produk, distribusi, dan pasar.'},
  brandPage:{title:'Merek & kemitraan',intro:'Pilihan untuk keluarga, fesyen, dan nutrisi.',body:'Kenali merek dan hubungan kerja sama dalam bisnis WINMAX. Merek sendiri, keagenan, dan usaha waralaba dikelola sesuai perannya masing-masing.',retailTitle:'Merek dan kegiatan ritel',retailText:'BB-SO adalah merek ritel ibu dan bayi sendiri; 99K merupakan usaha waralaba ritel pakaian wanita.'},
  brandDetails:{
   carefor:{title:'Carefor, perawatan ibu & bayi',intro:'Untuk kebersihan dan perawatan harian si kecil.',body:'Carefor merupakan merek dari Tiongkok. WINMAX, sebagai agen eksklusifnya di Indonesia, menjalankan pengembangan merek dan produk di pasar lokal.',facts:[['Hubungan kerja sama','Agen eksklusif Indonesia'],['Kategori','Kebersihan dan perawatan harian bayi'],['Produk pada foto','Minyak bayi, sampo, losion, dan sabun mandi']],note:'Spesifikasi, kesesuaian penggunaan, dan cara pakai mengikuti label serta petunjuk resmi setiap produk.',image:'carefor-products.jpg',alt:'Foto produk Carefor Baby: minyak bayi, sampo, losion, dan sabun mandi',rotate:true},
   nutrition:{title:'宝体安 · Produk nutrisi',intro:'Memperhatikan kebutuhan nutrisi keluarga.',body:'Probiotik dan produk nutrisi 宝体安 merupakan salah satu arah pengembangan merek WINMAX. Seri produk dan rencana pasar akan mengikuti materi yang dikonfirmasi secara resmi.',facts:[['Kategori','Probiotik dan produk nutrisi'],['Tahap saat ini','Rencana pengembangan pasar'],['Informasi produk','Diperbarui setelah materi resmi dikonfirmasi']],note:'Halaman ini menjelaskan arah bisnis, bukan klaim manfaat produk atau saran kesehatan.'},
   mimimilo:{title:'Mimimilo, merek sendiri',intro:'Membangun merek, berawal dari toko online.',body:'Mimimilo adalah arah pengembangan merek sendiri kami. Berawal dari toko online Mimilo yang sudah berjalan, dengan rencana kategori pakaian dan sepatu anak serta pengembangan rangkaian produk.',facts:[['Hubungan merek','Pengembangan merek sendiri'],['Dasar usaha','Toko online Mimilo'],['Rencana kategori','Pakaian dan sepatu anak']],note:'Produk merek baru dan jadwal peluncuran mengikuti pengumuman resmi berikutnya.'}
  },
  careers:{title:'Bertumbuh bersama WINMAX',intro:'Bawa keahlianmu ke dalam dunia merek, perdagangan, dan ritel.',body:'Kami menghargai orang yang bekerja dengan sungguh-sungguh, mau belajar, dan memahami pelanggan serta kerja sama tim. Berikut adalah bidang kerja tim; posisi yang tersedia, tanggung jawab, dan kompensasi mengikuti komunikasi rekrutmen.',areas:[['Merek & pengembangan bisnis','Komunikasi merek, kemitraan kanal, dan pelaksanaan kegiatan pasar.'],['Operasional e-commerce','Presentasi produk, konten, dan ritel online.'],['Gerai & layanan ritel','Penataan produk, layanan pelanggan, dan operasional gerai.']],applyTitle:'Ceritakan tentang dirimu',applyBody:'Kirim CV dan bidang yang diminati ke email kontak Indonesia. Cantumkan nama dan posisi yang diminati pada subjek email.',button:'Hubungi melalui email',subject:'Minat karier WINMAX — Nama / Posisi'},
  contact:{title:'Hubungi WINMAX',intro:'Mari berbicara tentang langkah kerja sama berikutnya.',body:'Untuk kerja sama merek, rantai pasok, ritel, atau pertanyaan karier, hubungi kami melalui email berikut.',china:'Kontak Tiongkok',indonesia:'Kontak Indonesia',email:'Tulis email',subject:'Pertanyaan kerja sama WINMAX',company:'Perusahaan induk',location:'Pasar bisnis',locationValue:'Indonesia',topics:[['Merek & rantai pasok','Keagenan merek, pasokan produk, dan perdagangan impor.'],['Kanal & ritel','Distribusi, gerai, dan kerja sama bisnis ritel.'],['Tim & karier','Mengenal perusahaan dan bidang kerja terkait.']],prompt:'Sertakan nama, perusahaan atau lokasi, serta topik yang ingin dibahas agar kami dapat memahami kebutuhan Anda.'},
  ctaTitle:'Mari temukan langkah berikutnya.',ctaBody:'Koneksi merek, rantai pasok, dan ritel dimulai dari sebuah percakapan.',ctaButton:'Hubungi kami',
  footerTagline:'Better Products. Better Life.',footerText:'Merek · Perdagangan · Ritel',footerNav:'Kenali WINMAX',footerContact:'Email kontak',rights:'Hak cipta dilindungi.',external:'Buka di jendela baru',notFound:'Halaman tidak ditemukan',notFoundBody:'Kembali ke beranda untuk mengenal WINMAX.'
 }
};
